openapi: 3.0.0
info:
  version: '1.0'
  title: Golang Clean Architecture Template
  description: This is a sample server for a Golang Clean Architecture Template.
  contact:
    name: Kelana Chandra Helyandika
    url: https://kelanach.cyclic.app/
    email: kelana.helyanedika@mhs.unsoed.ac.id
servers:
  - url: http://localhost:3000/api/v1
    description: Local Server V1

tags:
  - name: Auth
    description: Authentication related operations
  - name: User
    description: User related operations

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    InternalServerError:
      description: Internal Server Error
      type: object
      properties: 
        errors: 
          type: boolean 
          example: true
        message: 
          type: string 
          example: Internal Server Error

    AccountNotHaveAccess:
      description: Account Doesn't Have Access
      type: object
      properties: 
        errors: 
          type: boolean 
          example: true
        message: 
          type: string 
          example: Account Doesn't Have Access

    DataNotFound:
      description: Data Not Found
      type: object 
      properties:
        errors: 
          type: boolean
          example: true
        message: 
          type: string 
          example: Data Not Found

    DataInputNotValid:
      description: Input Not Valid
      type: object
      properties:
        errors:
          type: boolean
          example: true
        message:
          type: string
          example: Data not valid


paths:
# ! ------------------------ ---- ------------------------ ! #
# ! ------------------------ AUTH ------------------------ ! #
# ! ------------------------ ---- ------------------------ ! #
  /login:
    post:
      summary: Login for user 
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Success login 
          content:  
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Success Login
                  data: 
                    type: object
                    properties:
                      token:
                        type: string 
                      token_type:
                        type: string
                        example: JWT
                      expired_time:
                        type: string 
                        example: 30d
        '400':
          description: Data not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataInputNotValid'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'





# ! ------------------------ ---- ------------------------ ! #
# ! ------------------------ USERS ------------------------ ! #
# ! ------------------------ ---- ------------------------ ! #
  /users:
    get:
      summary: Get data users (admin only)
      tags:
        - User
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: false
          description: Page number
        - in: query
          name: per_page
          schema:
            type: integer
          required: false
          description: Limit data per page
      responses:
        '200':
          description: Get users data
          content:  
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: get users data
                  data: 
                    type: object
                    properties:
                      page:
                        type: integer 
                      per_page:
                        type: integer
                      total:
                        type: integer
                      users: 
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                            username:
                              type: string
                            role:
                              type: number
                            created_at:
                              type: string
                            updated_at:
                              type: string
        '401':
          description: Unathorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountNotHaveAccess'
        '400':
          description: Data not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataInputNotValid'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

    post:
      summary: Create new user by admin (role value = 1 (admin) || 2 (user))
      tags:
        - User
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                role:
                  type: number 
                  default: 2
      responses:
        '200':
          description: Success create new account
          content:  
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: boolean
                    example: false
                  message:
                    type: string
        '400':
          description: Data not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataInputNotValid'
        '401':
          description: Unathorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountNotHaveAccess'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'




  /users/{id}:
    get:
      summary: Get user data self info 
      tags:
        - User
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of user
      responses:
        '200':
          description: get user self info
          content:  
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: boolean
                    example: false
                  message:
                    type: string
                  data: 
                    type: object
                    properties:
                      id:
                        type: string 
                      username:
                        type: string
                      role:
                        type: number 
                      created_at: 
                        type: string
                      updated_at:
                        type: string
        '401':
          description: Unathorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountNotHaveAccess'
        '404':
          description: Data not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataNotFound'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'


    patch:
      summary: Change user data (username & role) (admin and self)
      tags:
        - User
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username: 
                  type: string 
                role:
                  type: number
      responses:
        '200':
          description: Success Change user data
          content:  
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: boolean
                    example: false
                  message:
                    type: string
        '401':
          description: Unathorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountNotHaveAccess'
        '404':
          description: Data not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataNotFound'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'


    delete:
      summary: Delete user data (admin only)
      tags:
        - User
      security:
        - bearerAuth: []
      parameters:
        - in: path 
          name: id
          schema:
            type: string
          required: true
          description: ID of user
      responses:
        '200':
          description: Success delete data 
          content:  
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: boolean
                    example: false
                  message:
                    type: string
        '401':
          description: Unathorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountNotHaveAccess'
        '404':
          description: Data not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataNotFound'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'





  /users/{id}/password:  
    patch:
      summary: Edit user password (self) 
      tags:
        - User
      security:
        - bearerAuth: []
      parameters:
        - in: path 
          name: id
          schema:
            type: string
          required: true
          description: ID of user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                old_password:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: success change user password
          content:  
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: boolean
                    example: false
                  message:
                    type: string
        '400':
          description: Data not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataInputNotValid'
        '401':
          description: Unathorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountNotHaveAccess'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'